### ISSUE TITLE
H264Transcoder This file looks very complicated,Is it possible to simplify the code design?

### ISSUE THREAD

**Issue by sgf** [ReferenceType/P2PVideocall#3]
[        private unsafe void Decode2(byte[] payload, int payloadOffset, int payloadCount, int w, int h)](https://github.com/ReferenceType/P2PVideocall/blob/master/ServiceProvider/Services/Video/H264/H264Transcoder.cs#L352)

This file looks very complicated. There are too many delegates used. And some concepts are too many. In fact, I mainly want to know how H264Sharp actually makes live calls.
Is it possible to simplify the code design?

**Comment by ReferenceType** [comment]
This project is currently a prototype. The service structure will be refactored, and you will see many abstractions in future updates.

Regarding your question, there are some examples in H264Sharp on how to encode and decode an image if you want a simple implementation.

In this application, I use an unreliable channel to send the encoded video stream. This is a non-trivial operation, especially with the LTR (Long Term Reference) feature, where you need to jitter buffer the incoming frames, order them, and report feedback from the decoder to the encoder.

Simply put, the encoded frames are sent to the transcoder and then placed into the jitter buffer. The buffer decides when to decode the frame, and the decoded frame is published so the UI can render it.

Raw decoded images are quite large and unmanaged (also on the WPF side with GDI). You have to handle buffered frames carefully to avoid memory bloat or excessive GC pressure. For this reason, raw images are pooled.

The second part of buffering occurs in the video handler because the images must be synced with audio, as they are independent streams. This means we have to buffer some raw images and publish them to the UI according to the current position of the audio.

There are plenty of caveats like rate control according to network status. There are some dead code around for my internal testing. Bare in mind i use this app to have calls cross countries with distance about 2000km daily, my personal experience indicates its stable. 
However in the future i intend to add couple more features such as remote desktop control and group calls, maybe user db. and plans on porting the UI on Avalonia and make the app cross platform as final goal.

**Comment by sgf** [comment]
Thanks for your suggestion.And your plan is great!
